# Generated by Django 4.2.3 on 2023-07-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_likes_dishid_alter_likes_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='dishPhoto',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
