# Generated by Django 4.2.3 on 2023-07-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_alter_likes_dishphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='dishId',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
