# Generated by Django 4.2.3 on 2023-07-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=20, unique=True)),
                ('dishName', models.CharField(max_length=20)),
                ('dishPhoto', models.ImageField(upload_to='post')),
                ('dishId', models.CharField(max_length=20, unique=True)),
                ('bio', models.CharField(max_length=500)),
                ('cusine', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
