# Generated by Django 4.2.3 on 2023-07-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bio',
            new_name='dishBio',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cusine',
            new_name='dishCusine',
        ),
        migrations.AddField(
            model_name='post',
            name='dishTime',
            field=models.IntegerField(default=0),
        ),
    ]
