# Generated by Django 4.2.3 on 2023-07-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_dishcusine_post_dishcuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dishId',
        ),
    ]
