# Generated by Django 4.2.3 on 2023-07-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_dishid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userId',
            field=models.CharField(max_length=20),
        ),
    ]
