# Generated by Django 4.2.3 on 2023-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dishPhoto',
            field=models.CharField(max_length=500),
        ),
    ]
