# Generated by Django 4.2.3 on 2023-07-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_dishphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dishId',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
