# Generated by Django 4.2.3 on 2023-07-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userId',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
