# Generated by Django 4.2.3 on 2023-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_alter_userprofile_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePhoto',
            field=models.ImageField(default='pics/blank-profile-picture.png', upload_to='pics'),
        ),
    ]
